# Generated by Django 5.2 on 2025-04-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('gu', models.CharField(max_length=50)),
                ('dong', models.CharField(blank=True, max_length=50, null=True)),
                ('area_type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('success_prob', models.FloatField()),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
